#!/bin/sh
SESSION=eve-ng
HOSTN=eve-ng.kau.nul

tmux new-session -d -s $SESSION

tmux rename-window "MikroTik"
tmux send-keys -t $SESSION:1.1 "telnet $HOSTN 32769" Enter

tmux new-window -n "ISP1"
tmux send-keys -t $SESSION:2.1 "telnet $HOSTN 32773" Enter

tmux new-window -n "ISP2"
tmux send-keys -t $SESSION:3.1 "telnet $HOSTN 32774" Enter

tmux new-window -n "ISP0"
tmux send-keys -t $SESSION:4.1 "telnet $HOSTN 32776" Enter

tmux new-window -n "VPC"
tmux send-keys -t $SESSION:5.1 "telnet $HOSTN 32775" Enter
tmux split-window -v -t $SESSION:5.1 "telnet $HOSTN 32777" Enter
tmux split-window -v -t $SESSION:5.2 "telnet $HOSTN 32770" Enter
tmux split-window -v -t $SESSION:5.3 "telnet $HOSTN 32771" Enter
tmux split-window -v -t $SESSION:5.4 "telnet $HOSTN 32772" Enter

tmux select-layout even-vertical

tmux select-window -t 5

tmux attach-session -t $SESSION

